services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      # - "./log:/app/log"
      # - "./database.db:/app/database.db"
    ports:
      - "8000:8000"
