"""Make rss_source a foreign key

Revision ID: aa3bafb8a9d0
Revises: 
Create Date: 2024-05-13 15:37:40.538312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "aa3bafb8a9d0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# https://alembic.sqlalchemy.org/en/latest/batch.html#dealing-with-constraints
# https://stackoverflow.com/questions/29153930/changing-constraint-naming-conventions-in-flask-sqlalchemy
naming_convention = {
    "pk": "pk_%(table_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "RSSHubFeedEntry", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.create_foreign_key(
            "fk_RSSHubFeedEntry_rss_source_RSSHubFeedSource",
            "RSSHubFeedSource",
            ["rss_source"],
            ["name"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "RSSHubFeedEntry", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_constraint(
            "fk_RSSHubFeedEntry_rss_source_RSSHubFeedSource", type_="foreignkey"
        )

    # ### end Alembic commands ###
